### ISSUE TITLE
Installs custom tinyxml version

### ISSUE THREAD

**Issue by xqms** [fzi-forschungszentrum-informatik/fzi_icl_core#1]
Hi,

it seems that this package installs its own tinyxml version:

```
$ dpkg -L ros-indigo-fzi-icl-core | grep tiny
/opt/ros/indigo/include/tinyxml
/opt/ros/indigo/include/tinyxml/tinystr.h
/opt/ros/indigo/include/tinyxml/tinyxml.h
/opt/ros/indigo/lib/libtinyxml.so
/opt/ros/indigo/share/tinyxml
/opt/ros/indigo/share/tinyxml/tinyxml-config.cmake
```

This is dangerous, since other packages using `find_package(tinyxml)` will now find this version. An example is the `gazebo_ros_pkgs` package, which will not compile with your tinyxml version on my system:

```
Errors << gazebo_ros:make /var/lib/jenkins/jobs/centauro/workspace/build/_logs/gazebo_ros/build.make.000.log
/var/lib/jenkins/jobs/centauro/workspace/src/gazebo_ros_pkgs/gazebo_ros/src/gazebo_ros_api_plugin.cpp: In member function ‘void gazebo::GazeboRosApiPlugin::updateSDFAttributes(TiXmlDocument&, std::string, gazebo::math::Vector3, gazebo::math::Quaternion)’:
/var/lib/jenkins/jobs/centauro/workspace/src/gazebo_ros_pkgs/gazebo_ros/src/gazebo_ros_api_plugin.cpp:2009:48: error: no matching function for call to ‘TiXmlElement::SetAttribute(const char [5], std::string&)’
     model_tixml->SetAttribute("name",model_name);
                                                ^
/var/lib/jenkins/jobs/centauro/workspace/src/gazebo_ros_pkgs/gazebo_ros/src/gazebo_ros_api_plugin.cpp:2009:48: note: candidates are:
In file included from /var/lib/jenkins/jobs/centauro/workspace/src/gazebo_ros_pkgs/gazebo_ros/src/gazebo_ros_api_plugin.h:32:0,
                 from /var/lib/jenkins/jobs/centauro/workspace/src/gazebo_ros_pkgs/gazebo_ros/src/gazebo_ros_api_plugin.cpp:25:
/opt/ros/indigo/include/tinyxml/tinyxml.h:1056:7: note: void TiXmlElement::SetAttribute(const char*, const char*)
  void SetAttribute( const char* name, const char * _value );
```

I would recommend not installing the library, or installing it under a non-standard name.

**Comment by xqms** [comment]
Quick update: I have some changes that allow building fzi_icl_core using a system installation of tinyxml. I won't have time to properly clean that up this week, but essentially removing the tinyxml directory and removing all icmaker dependencies on tinyxml works just fine. Hopefully I can get around to submitting a PR next week.

**Comment by davetcoleman** [comment]
@xqms this fix would be very appreciated, I was using the Schunk SVH Driver just now and it depends on this package. When I installed it all from Ubuntu debians my whole MoveIt! setup broke as I reported [here](http://answers.ros.org/question/267743/conflicting-libtinyxml-libraries-kinetic/?answer=267744#post-id-267744). I used ``dpkg -S libtinyxml.so`` to track the problem down to this package.

**Comment by fmauch** [comment]
Thanks for the reminder. Could you test it with the current version please?

**Comment by davetcoleman** [comment]
I don't think I can test the previous issue until you release this back into the ROS distro and then wait for the next ROS debian sync. Otherwise I'd just be building from source, which won't cause collisions with TinyXML would it?

**Comment by fmauch** [comment]
@davetcoleman a new version got synced into ROS, so you could give it another try :)

**Comment by davetcoleman** [comment]
I uninstalled the old version, installed the new version, and rebuilt my workspace from scratch... and now it works. Thanks!!
